-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 19:09:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gift_certificates
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gift_certificates` DEFAULT CHARACTER SET utf8 ;
USE `gift_certificates` ;

-- -----------------------------------------------------
-- Table `gift_certificates`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(305) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`gift_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`gift_certificate` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(305) NULL,
  `description` VARCHAR(2000) NULL,
  `price` DECIMAL(5) NULL,
  `duration` INT UNSIGNED NULL,
  `create_date` TIMESTAMP(6) NULL,
  `last_update_date` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates`.`m2m_certificates_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates`.`m2m_certificates_tags` (
  `gift_certificate_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`gift_certificate_id`, `tag_id`),
  INDEX `tag_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `gift_certificate`
    FOREIGN KEY (`gift_certificate_id`)
    REFERENCES `gift_certificates`.`gift_certificate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `gift_certificates`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
